# Generated by Django 2.2.18 on 2021-03-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0007_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bookmark_date_display",
            field=models.CharField(
                choices=[
                    ("relative", "Relative"),
                    ("absolute", "Absolute"),
                    ("hidden", "Hidden"),
                ],
                default="relative",
                max_length=10,
            ),
        ),
    ]
