# Generated by Django 3.2.6 on 2021-10-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0009_bookmark_web_archive_snapshot_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bookmark_link_target",
            field=models.CharField(
                choices=[("_blank", "New page"), ("_self", "Same page")],
                default="_blank",
                max_length=10,
            ),
        ),
    ]
