# Generated by Django 3.2.14 on 2022-08-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0015_feedtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="shared",
            field=models.BooleanField(default=False),
        ),
    ]
