# Generated by Django 4.1 on 2022-11-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0017_userprofile_enable_sharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_url',
            field=models.BooleanField(default=False),
        ),
    ]
