# Generated by Django 4.1 on 2023-02-13 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0018_userprofile_display_url'),
        ('bookmarks', '0019_userprofile_enable_favicons'),
    ]

    operations = [
    ]
