# Generated by Django 4.1.7 on 2023-05-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0020_userprofile_tag_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="display_url",
            field=models.BooleanField(default=False),
        ),
    ]
