# Generated by Django 4.1.9 on 2023-05-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0022_bookmark_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="permanent_notes",
            field=models.BooleanField(default=False),
        ),
    ]
