# Generated by Django 4.1.9 on 2023-08-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0023_userprofile_permanent_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="enable_public_sharing",
            field=models.BooleanField(default=False),
        ),
    ]
