# Generated by Django 4.1.9 on 2023-09-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0024_userprofile_enable_public_sharing"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="search_preferences",
            field=models.JSONField(default=dict),
        ),
    ]
