# Generated by Django 4.1.13 on 2024-02-04 20:47

import bookmarks.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0025_userprofile_search_preferences"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        max_length=2048,
                        validators=[bookmarks.validators.BookmarkURLValidator()],
                        unique=True,
                    ),
                ),
                (
                    "website_title",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("website_description", models.TextField(blank=True, null=True)),
                (
                    "web_archive_snapshot_url",
                    models.CharField(blank=True, max_length=2048),
                ),
                (
                    "favicon_file",
                    models.CharField(blank=True, max_length=512),
                ),
                (
                    "created",
                    models.DateTimeField(default=timezone.now)
                )
            ],
        ),
        migrations.AddField(
            model_name="bookmark",
            name="link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bookmarks.link",
            ),
        ),
    ]
