# Generated by Django 5.0.2 on 2024-03-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0026_userprofile_custom_css"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bookmark_description_display",
            field=models.CharField(
                choices=[("inline", "Inline"), ("separate", "Separate")],
                default="inline",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bookmark_description_max_lines",
            field=models.IntegerField(default=1),
        ),
    ]
