# Generated by Django 4.1.13 on 2024-02-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0027_migrate_urls_to_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookmark",
            name="favicon_file",
        ),
        migrations.RemoveField(
            model_name="bookmark",
            name="url",
        ),
        migrations.RemoveField(
            model_name="bookmark",
            name="web_archive_snapshot_url",
        ),
        migrations.RemoveField(
            model_name="bookmark",
            name="website_description",
        ),
        migrations.RemoveField(
            model_name="bookmark",
            name="website_title",
        ),
    ]
