# Generated by Django 5.0.2 on 2024-04-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0030_bookmarkasset"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="enable_automatic_html_snapshots",
            field=models.BooleanField(default=True),
        ),
    ]
