# Generated by Django 5.0.3 on 2024-05-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0034_bookmark_preview_image_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="auto_tagging_script",
            field=models.TextField(blank=True),
        ),
    ]
