# Generated by Django 5.0.3 on 2024-05-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0034_bookmark_preview_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="preview_image_file",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
