# Generated by Django 5.0.3 on 2024-05-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0035_userprofile_tag_grouping"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="auto_tagging_rules",
            field=models.TextField(blank=True),
        ),
    ]
