# Generated by Django 5.0.8 on 2024-09-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0038_globalsettings_guest_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="enable_link_prefetch",
            field=models.BooleanField(default=False),
        ),
    ]
