# Generated by Django 5.1.1 on 2024-09-21 08:13

from django.db import migrations
from django.db.models import F, Q

from bookmarks.models import Bookmark


def forwards(apps, schema_editor):
    Bookmark.objects.filter(
        Q(title__isnull=True) | Q(title__exact=""),
        website_title__isnull=False,
    ).update(title=F("website_title"))

    Bookmark.objects.filter(
        Q(description__isnull=True) | Q(description__exact=""),
        website_description__isnull=False,
    ).update(description=F("website_description"))


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0040_userprofile_items_per_page_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, reverse),
    ]
