# Generated by Django 5.1.1 on 2024-09-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0041_merge_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="custom_css_hash",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
