# Generated by Django 5.1.1 on 2024-11-12 00:16

from django.db import migrations, models


def update_latest_snapshots(apps, schema_editor):
    Bookmark = apps.get_model("bookmarks", "bookmark")
    for bookmark in Bookmark.objects.all():
        snapshots = bookmark.bookmarkasset_set.filter(status="complete").order_by(
            "-date_created"
        )
        if snapshots:
            bookmark.latest_snapshot_id = snapshots[0].id
        bookmark.save()


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0042_userprofile_custom_css_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="latest_snapshot_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(update_latest_snapshots),
    ]
