# Generated by Django 5.1.1 on 2024-11-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0042_userprofile_custom_css_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="locally_archived_snapshot_link",
            field=models.BooleanField(default=False),
        ),
    ]
