# Generated by Django 5.1.5 on 2025-02-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0042_userprofile_custom_css_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="collapse_side_panel",
            field=models.BooleanField(default=False),
        ),
    ]
