# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0045_userprofile_hide_bundles_bookmarkbundle"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="access_count",
            field=models.IntegerField(default=0),
        ),
    ]