# Generated by Django 5.2.3 on 2025-08-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0045_userprofile_hide_bundles_bookmarkbundle"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="url_normalized",
            field=models.CharField(blank=True, db_index=True, max_length=2048),
        ),
    ]
