# Generated by Django 5.1.9 on 2025-06-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0045_bookmarkbundle"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmarkbundle",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
