# Generated by Django 5.1.9 on 2025-06-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0046_bookmarkbundle_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="hide_bundles",
            field=models.BooleanField(default=False),
        ),
    ]
