# Generated by Django 5.2.3 on 2025-08-22 08:28

from django.db import migrations
from bookmarks.utils import normalize_url


def populate_url_normalized(apps, schema_editor):
    Bookmark = apps.get_model("bookmarks", "Bookmark")

    for bookmark in Bookmark.objects.all():
        bookmark.url_normalized = normalize_url(bookmark.url)
        bookmark.save(update_fields=["url_normalized"])


def reverse_populate_url_normalized(apps, schema_editor):
    Bookmark = apps.get_model("bookmarks", "Bookmark")
    Bookmark.objects.all().update(url_normalized="")


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0046_add_url_normalized_field"),
    ]

    operations = [
        migrations.RunPython(
            populate_url_normalized,
            reverse_populate_url_normalized,
        ),
    ]
