# Generated by Django 5.2.3 on 2025-08-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0047_populate_url_normalized_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="default_mark_shared",
            field=models.BooleanField(default=False),
        ),
    ]
