# Generated by Django 5.2.5 on 2025-12-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0051_fix_normalized_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='webhook_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='webhook_tag',
            field=models.CharField(default='webhook'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='webhook_url',
            field=models.URLField(default='', null=True),
        ),
    ]
