# Generated by Django 5.2.5 on 2025-11-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0051_fix_normalized_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="openai_api_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="openai_model",
            field=models.CharField(blank=True, default="gpt-5-nano", max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="openai_tag_vocabulary",
            field=models.TextField(blank=True),
        ),
    ]
