# Generated by Django 5.2.5 on 2025-11-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0051_fix_normalized_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="ai_api_key",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="ai_model",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="ai_tag_vocabulary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="ai_base_url",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
