# Generated by Django 5.2.5 on 2025-12-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookmarks",
            "0052_userprofile_webhook_enabled_userprofile_webhook_tag_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="webhook_auth_password",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="webhook_auth_username",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="webhook_use_basic_auth",
            field=models.BooleanField(default=False),
        ),
    ]
