# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0052_bookmarkusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="enable_usage_tracking",
            field=models.BooleanField(default=False),
        ),
    ]
