# Generated by Django 6.0 on 2026-02-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0053_migrate_api_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkbundle',
            name='filter_shared',
            field=models.CharField(choices=[('off', 'All'), ('yes', 'Shared'), ('no', 'Unshared')], default='off', max_length=3),
        ),
        migrations.AddField(
            model_name='bookmarkbundle',
            name='filter_unread',
            field=models.CharField(choices=[('off', 'All'), ('yes', 'Unread'), ('no', 'Read')], default='off', max_length=3),
        ),
    ]
