# Generated by Django 6.0.7 on 2026-09-04 00:51

from django.db import migrations, models


def forwards(apps, schema_editor):
    UserProfile = apps.get_model("bookmarks", "UserProfile")
    UserProfile.objects.filter(web_archive_integration="enabled").update(
        enable_web_archiving=True, default_web_archive=True
    )
    Bookmark = apps.get_model("bookmarks", "Bookmark")
    Bookmark.objects.filter(owner__profile__web_archive_integration="enabled").update(
        web_archive=True
    )


def reverse(apps, schema_editor):
    UserProfile = apps.get_model("bookmarks", "UserProfile")
    UserProfile.objects.filter(enable_web_archiving=True).update(
        web_archive_integration="enabled"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0054_bookmarkbundle_filter_shared_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="web_archive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_web_archive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="enable_web_archiving",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(forwards, reverse),
        migrations.RemoveField(
            model_name="userprofile",
            name="web_archive_integration",
        ),
    ]
