# Generated by Django 6.0.7 on 2026-09-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0054_bookmarkbundle_filter_shared_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="language",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
