version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    groups:
      docs-security:
        applies-to: security-updates
        patterns:
          - "*"
