version: '3'

services:
  linkding:
    container_name: "${LD_CONTAINER_NAME:-linkding}"
    image: sissbruecker/linkding:latest
    ports:
      - "${LD_HOST_PORT:-9090}:9090"
    volumes:
      - "${LD_HOST_DATA_DIR:-./data}:/etc/linkding/data"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: linkding_db
    restart: unless-stopped
    volumes:
      - linkding_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_USER=linkding
      - POSTGRES_DB=linkding

volumes:
  linkding_db:
